### PR TITLE
changes the color of the buy buttons

### PR DESCRIPTION
**Pull request by Darwinny**
here is a test to see if I’m taking all the right steps to make changes to HTML and CSS. I changed the color of the buy buttons in CSS. I created a branch of the the master, committed, published, and then put in a pull request. Can you merge this into the master and then I can see if everything “takes” on my side?

### CODE REVIEW

**Comment by JasonHorsley2** [comment]
I think it worked. I've got the bg color of the buy button as the new light
green (145,189,73) and I didn't lose any of my work, so I think we merged
alright.

Yay! Keep a local copy though, i'd like to spend the rest of the day on
pubbly2016 as well, and I'm still pretty new with github, so lets play it
safe for the first few days at least.

**Comment by Darwinny** [comment]
ok cool. I'll hold off until you give me the go ahead.

**Comment by JasonHorsley2** [comment]
No no, please feel free to make some more branches and pull requests. I
just want you to keep a local copy as a backup. I'm new at git, so I may
make some mistakes. But now is the time for us to practice the system.
Before it gets too complicated of valuable.

**Comment by Darwinny** [comment]
That is very true . . . I will venture forth. I have backups of everything . . . that is what I'm pulling from.

**Pull request merged**
