### PR TITLE
Revision to top

### PR DESCRIPTION
**Pull request by Darwinny**
and other little bits

### CODE REVIEW

**Comment by JasonHorsley2** [comment]
Susan,

Your commits are conflicting. In the "update to circle", PubblyStyle.css, line 65, you removed 

 -	padding-bottom: 20px;
and added
 +	padding-bottom: 1%;
 
Then, in "scalable top", PubblyStyle.css, line 65, you removed

-	padding-bottom:30px;
and added
+	padding-bottom: 20px;

GitHub doesn't know which you want, and it seems both files were based on a different master. I think "scalable top" is probably your most recent work. If you could, please double check me on this. Try to merge on your end and create a clean push.

This stuff gets complicated fast...

Thanks!

Jason

**Comment by Darwinny** [comment]
I saw that after I requested the pull request. I was surprised because it looked like I had cleared away all conflicts. I will look at it

**Comment by Darwinny** [comment]
I think I resolved it . . . if you see a conflict just pick what you think is right and I'll fix later if necessary.

In the work you did on the buttons there with two icon images that had the id=heartsign . . . I changed the magnifying glass to id=magnifi . . . it had not effect on the page

-- I didn't even see the conflict that you saw. It's weird

**Comment by Darwinny** [comment]
I'd like to merge the whole branch "revision to top"

the "Merge remote-tracking branch. . ." was the most recent addition to that branch ) this morning

before that was "update circles to the top"

before that was "scaleable top"

**Comment by JasonHorsley2** [comment]
Merged successfully, looks good,

**Pull request merged**
